### ISSUE TITLE
Bugs.

### ISSUE THREAD

**Issue by SaudTauqeer** [relay-chat/RIPs#1]
* On xs small devices there is no padding/margin on the text field and the content on the bottom is being cut-off by browser border.
* On Firefox and Chrome, If you switch a new tab. it takes around 20 seconds something to click the extension icon repeatedly to make it appear again. This happens if you open the browser after closing.
* (I have already mentioned this issue to Sam on the Relay app.) The timeZones rely on the local time of the machine. Hence TimeStamps can be inconsistent.
* There is an invisible wall on the left side while dragging ( Not sure if this is a browser limitation).
* If you refresh the app while using it multiplies the number of online users in most cases. such as 2 to 4 and then refresh again or go to another page it becomes 8. 
* Stickers should be a little big in size. Can't really see the emoji after sending. 
* If I click the save icon, the icon next to the burger menu. Click it twice and users will multiply.

**Comment by SaudTauqeer** [comment]
Clarification of the invisible wall drag issue. There is no wall, Instead if you drag it slowly it works as intended, but if you try to drag it a little bit faster than that it will drop midway. By faster, I mean regular mouse usage.

**Comment by SaudTauqeer** [comment]
Kudos for working on it extensively and working actively on user feedback. Wish you good luck @relayChatTeam.

**Comment by sewinter** [comment]
Hey @SaudTauqeer, thanks so much for your feedback! We fixed the fixed the num online issues with the latest release (v33) but will get to work on the others. 

You shouldn't have to click the extension icon to make the chat appear. Was it not loading without clicking the icon? Also, does this happen on certain sites in particular? 

Thanks again.

**Comment by SaudTauqeer** [comment]
@sewinter Thanks for the good work.
I think the most I faced this issue was on localhost3000. Have to click multiple times to make it appear.

**Comment by sewinter** [comment]
Hey @SaudTauqeer we got to all of these! The ones that require extension updates will come out in the next Chrome release. 

Thanks again for your feedback!
