### ISSUE TITLE
Chatbox losing text when switching windows

### ISSUE THREAD

**Issue by ASteinheiser** [relay-chat/RIPs#10]
I'm not sure if this is intentional, but I was trying to open a new window to copy some text, then when I switched back, I saw that my text was gone from the chat box.

**Comment by sewinter** [comment]
@ASteinheiser Thanks for that feedback. We definitely don't want you losing your draft. I'll make sure a fix goes into the next release.

**Comment by sewinter** [comment]
@ASteinheiser this is now fixed in Native and Firefox. Waiting on Google to approve :). Thanks again for flagging it.
