### ISSUE TITLE
Links without http:// prefix don't open properly

### ISSUE THREAD

**Issue by ASteinheiser** [relay-chat/RIPs#11]
For example, I typed the url: react-rpg.com and when I clicked it, it took me to my current url with that appended to the end. I would've expected it to realize it's a different site and not a route on the current site.

**Comment by sewinter** [comment]
Nice find! Definitely a bug. We'll fix it right away.

**Comment by sewinter** [comment]
@ASteinheiser this should now be fixed on Relay Native (and will be fixed in the extension with the next release--about a week or so).
