### ISSUE TITLE
Autocompleting user names while typing

### ISSUE THREAD

**Issue by ASteinheiser** [relay-chat/RIPs#12]
It would be cool if it could autocomplete the names other other users who have posted in the channel.

**Comment by sewinter** [comment]
@ASteinheiser we do have tab autocompletion of usernames for mentions, but we really should show some indication that autocompletion is available.

**Comment by ASteinheiser** [comment]
Yeah, it would be cool if it showed the user's name that you were about to complete, then allow you to use arrow keys up and down to select different user's with the same characters that you've typed. And having the remaining autocompleted characters be a sorta greyed out text color.

Ex. Type "An" shows "Andrew". Then if I press down arrow, it might show "Angel", down arrow again shows "AnotherName".

**Comment by sewinter** [comment]
Hey @ASteinheiser! You'll be happy to know this feature will be in the next version on Chrome! Marking as closed.
