### ISSUE TITLE
Suggestion: Mobile menu header should have down chevron to indicate close function

### ISSUE THREAD

**Issue by ASteinheiser** [relay-chat/RIPs#13]
It wasn't clear to me as to how to close the mobile view. Maybe a down chevron on the left could indicate that this is closable by clicking.
![screen shot 2019-02-23 at 2 06 25 pm](https://user-images.githubusercontent.com/9949512/53291683-7464ae00-3774-11e9-9625-b5ab65df8ac5.png)

**Comment by sewinter** [comment]
I completely agree! This is next up on our list. We also want to show the chevron in any loading screen. It's especially important on mobile to make closing the app as simple as possible given that the expanded view takes up the whole screen.

**Comment by sewinter** [comment]
@ASteinheiser this is now live on Relay Native. Please let me know what you think of the design. Thanks again for your feedback!

**Comment by ASteinheiser** [comment]
Nice! I was originally thinking the chevron next to the domain name, but it looks good how you have it now. It's consistent with the bottom tray design.

**Comment by sewinter** [comment]
Thanks, glad you like it 😄!
