### ISSUE TITLE
Script tag for embedding app not working on subdomain

### ISSUE THREAD

**Issue by ASteinheiser** [relay-chat/RIPs#15]
I clicked on the website owners section and copied the script tag into my site's index.html .
I have not tested on my naked url yet (react-rpg.com), however I tried staging.react-rpg.com and got this error:

GET Failed to load resource: the server responded with a status of 401 (Unauthorized) net::ERR_ABORTED 401 (Unauthorized)

And my network shows that I am sending the correct API key as a query parameter.

**Comment by sewinter** [comment]
@ASteinheiser we initially configured the service to require each subdomain to be authorized separately from each other and from the TLD, e.g., test.herokuapp.com would have a different API key than herokuapp.com, but your issue brings up a good point. If you're using the top-level domain's API key, that API key should also validate any subdomain. 

We just shipped a version that checks for just that, so your app should work now. Sorry about the confusion and thanks for your feedback.

**Comment by ASteinheiser** [comment]
Ah I see! That makes sense.

And yay! Works like a charm  🎉

**Comment by ASteinheiser** [comment]
@sewinter Just a quick question... Should the Relay Native site be showing that I have validated my domain when I only have the script tag on the staging subdomain? Or will it not show my site as validated until I push the changes to the root domain?
