### ISSUE TITLE
Moving the little R icon is tedious

### ISSUE THREAD

**Issue by birchmd** [relay-chat/RIPs#3]
When I try to move the app's icon around I need to do so very slowly because if my mouse leaves the icon then it stops moving. So I need to click and drag, but be very careful that my dragging does not leave the icon.

Technical notes:
OS: Ubuntu 18.04
Browser: Firefox 64.0 (64-bit)

**Comment by sewinter** [comment]
Hi @birchmd. Thanks for your feedback! We'll take a look at that right away.

**Comment by sewinter** [comment]
@birchmd marking this as closed, as it's been fixed in 0.0.35. Thanks again for your feedback!
