### ISSUE TITLE
Multiple Page Opening

### ISSUE THREAD

**Issue by refjosh** [relay-chat/RIPs#4]
Hey Sam, 

-Sorry I'm late with the feedback. I kinda had problem logging to my Github account using Chrome. 
Alright, moving on. 

-First of all, cheers for the work done. It blew my mind after it took me some few minutes to figure out what it's all about. It's really amazing 

-But there's something I believe can be fixed. Anytime I get mentioned on another domain and I try to click on the link from the inbox, it opens two tabs for that domain, leaving me to do the work of closing the other tab. 

-Still, Cheers 👍🏽

Please Note:
- Browser: Chrome Version 71.0.3578.98

**Comment by sewinter** [comment]
@joshtru thanks for your kind words. That means a lot to us. Relay's been a labor of love. 

We'll take a look at that bug right away. Should be a relatively easy fix, but we might have to wait for Chrome to approve our changes. Thanks for your feedback. We'll keep you posted!

**Comment by sewinter** [comment]
Hey @joshtru! Thanks again for your feedback. We just implemented a fix. It'll be out in the next Chrome release. Closing this for now.
