### ISSUE TITLE
UI/UX improvements.

### ISSUE THREAD

**Issue by SaudTauqeer** [relay-chat/RIPs#6]
* If Relay is closed from the extension tray, it should turn its the icon to gray and when you click it again it should show the normal Relay color. (Like React dev tools) Helps user know that Relay is loading as it takes some time to load up.
* If Relay chat-box is open and try to scroll it through the chat box it starts to stutter (sometimes) and if you drag faster it will let go of the Relay head.
* A white mode should be available too, some users prefer white mode. 
* When an update drops/news about Relay, You could send out a Relay-wide notification or show in chat.
* When the users of Relay increase so would the number of messages exchanged. Introducing a Slack like (You have 52 unread messages click here to see them) system would improve UX and give a smoother experience.
* Trending should be Trending Top 10 or something close to that, because when the chat rooms would increase there would be a long list of numbers showing chat rooms. This would also give users a sense of involvement if they regularly participate in their favorite chat room and they see it on top 10.
* Relay is currently fetching local machine time when I was developing an app which had to manage user and involves timezones and scheduling. A Reddit user suggested me this solution, a more accurate approach would be fetching user time based on the request IP but as Relay values, privacy above all this might work.

## Solution for user time.
The time-zone offset is the difference, in minutes, between UTC and local time. Note that this means that the offset is positive if the local timezone is behind UTC and negative if it is ahead. For example, if your time zone is UTC+10 (Australian Eastern Standard Time), -600 will be returned. Daylight savings time prevents this value from being a constant even for a given locale
Timezones can be seen as "relative to UTC". Look at this map: https://www.timeanddate.com/time/map/. See the bottom X-axis of the map? UTC is at the center and the timezones are + or - from UTC. I live in the USA in Central Time (commonly represented as -0600). https://en.wikipedia.org/wiki/Central_Time_Zone
So, if you know the Timezone offset, you can figure out their timezone. Just make a function called "getTimezone()..." and the function can just be a case-statement where you take their timezone offset and return the respective timezone in human-readable language.

**Comment by SaudTauqeer** [comment]
* A facebook like mention feature would help too.

**Comment by sewinter** [comment]
Hey @SaudTauqeer, we got to all of these except for white mode, which is on our roadmap, but we won't get to it for a while. Thanks for your feedback! Closing this for now.

**Comment by SaudTauqeer** [comment]
Great work on a fast pace.
