### ISSUE TITLE
Use different wording for sound in settings

### ISSUE THREAD

**Issue by redant333** [relay-chat/RIPs#9]
Using "Not Muted" in settings looks confusing, especially when turned off (i.e. it is not "Not muted"). Use "Audible notifications" or something similar (or "Muted" if you are OK with reversing the meaning of the switch).

**Comment by sewinter** [comment]
@redant333, thanks, that's great feedback. "Not Muted" is confusing as you said and just plain bad UX. I'll make sure a fix goes into the next release.

**Comment by sewinter** [comment]
@redant333 this is now fixed in Firefox. Just waiting on the Google approval process for Chrome. The new copy is just "Chat Sounds". Thanks again for flagging :)
